name: patch_app
description: "Patch the app by combining shorebird code push and terminate restart"
version: 0.0.1
homepage: https://github.com/lamnhan066/patch_app

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.24.5"

dependencies:
  flutter:
    sdk: flutter
  shorebird_code_push: ^2.0.4
  terminate_restart: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
