name: patch_app
description: "A lightweight helper to patch your Flutter app at runtime using shorebird\_code\_push and terminate\_restart"
version: 0.1.0
homepage: https://github.com/lamnhan066/patch_app

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  shorebird_code_push: ^2.0.4
  terminate_restart: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
